/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashVideoRouteImport } from './routes/_dash.video'
import { Route as DashUploadRouteImport } from './routes/_dash.upload'
import { Route as DashSignRouteImport } from './routes/_dash.sign'
import { Route as DashLiveRouteImport } from './routes/_dash.live'
import { Route as DashInsightsRouteImport } from './routes/_dash.insights'
import { Route as DashHistoryRouteImport } from './routes/_dash.history'
import { Route as DashGesturesRouteImport } from './routes/_dash.gestures'
import { Route as DashAnalyticsRouteImport } from './routes/_dash.analytics'

const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashVideoRoute = DashVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => DashRoute,
} as any)
const DashUploadRoute = DashUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashRoute,
} as any)
const DashSignRoute = DashSignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => DashRoute,
} as any)
const DashLiveRoute = DashLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashRoute,
} as any)
const DashInsightsRoute = DashInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashRoute,
} as any)
const DashHistoryRoute = DashHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashRoute,
} as any)
const DashGesturesRoute = DashGesturesRouteImport.update({
  id: '/gestures',
  path: '/gestures',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof DashAnalyticsRoute
  '/gestures': typeof DashGesturesRoute
  '/history': typeof DashHistoryRoute
  '/insights': typeof DashInsightsRoute
  '/live': typeof DashLiveRoute
  '/sign': typeof DashSignRoute
  '/upload': typeof DashUploadRoute
  '/video': typeof DashVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof DashAnalyticsRoute
  '/gestures': typeof DashGesturesRoute
  '/history': typeof DashHistoryRoute
  '/insights': typeof DashInsightsRoute
  '/live': typeof DashLiveRoute
  '/sign': typeof DashSignRoute
  '/upload': typeof DashUploadRoute
  '/video': typeof DashVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/gestures': typeof DashGesturesRoute
  '/_dash/history': typeof DashHistoryRoute
  '/_dash/insights': typeof DashInsightsRoute
  '/_dash/live': typeof DashLiveRoute
  '/_dash/sign': typeof DashSignRoute
  '/_dash/upload': typeof DashUploadRoute
  '/_dash/video': typeof DashVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/gestures'
    | '/history'
    | '/insights'
    | '/live'
    | '/sign'
    | '/upload'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/gestures'
    | '/history'
    | '/insights'
    | '/live'
    | '/sign'
    | '/upload'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/_dash/analytics'
    | '/_dash/gestures'
    | '/_dash/history'
    | '/_dash/insights'
    | '/_dash/live'
    | '/_dash/sign'
    | '/_dash/upload'
    | '/_dash/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/video': {
      id: '/_dash/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof DashVideoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/upload': {
      id: '/_dash/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashUploadRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/sign': {
      id: '/_dash/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof DashSignRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/live': {
      id: '/_dash/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof DashLiveRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/insights': {
      id: '/_dash/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof DashInsightsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/history': {
      id: '/_dash/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof DashHistoryRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/gestures': {
      id: '/_dash/gestures'
      path: '/gestures'
      fullPath: '/gestures'
      preLoaderRoute: typeof DashGesturesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashGesturesRoute: typeof DashGesturesRoute
  DashHistoryRoute: typeof DashHistoryRoute
  DashInsightsRoute: typeof DashInsightsRoute
  DashLiveRoute: typeof DashLiveRoute
  DashSignRoute: typeof DashSignRoute
  DashUploadRoute: typeof DashUploadRoute
  DashVideoRoute: typeof DashVideoRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashGesturesRoute: DashGesturesRoute,
  DashHistoryRoute: DashHistoryRoute,
  DashInsightsRoute: DashInsightsRoute,
  DashLiveRoute: DashLiveRoute,
  DashSignRoute: DashSignRoute,
  DashUploadRoute: DashUploadRoute,
  DashVideoRoute: DashVideoRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
